### ISSUE TITLE
Ne pas avoir à scroller après l'authent

### ISSUE THREAD

**Issue by juherr** [locher/Wishlist#14]
Il ne faudrait pas avoir à re-scroller après avoir cliqué sur "Je suis X".

Une solution serait d'avoir des ancres sur les personnes, et que le bouton "Je suis X" lance l'url `....index.php#X` au lieu de `....index.php`

**Comment by locher** [comment]
C'est vrai, mais que dans une petite partie des cas, celle où tu veux accéder à ta liste après le login.
Dans le cas où t'y vas pour voir la liste des autres, que ça t'emmène à la tienne est pas une bonne chose.

**Comment by juherr** [comment]
En effet, reste à savoir ce que tu fais le plus :)
